<?php

declare(strict_types=1);

namespace App\Models;

use DateTimeInterface;
use Illuminate\Database\Eloquent\Concerns\HasVersion4Uuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Schema;

/**
 * Application base model.
 *
 * Every domain model extends this instead of Eloquent's Model directly, so
 * cross-cutting concerns live in one place:
 *
 *  - UUID (version 4) primary keys — generated by HasVersion4Uuids.
 *  - Soft deletes — rows are flagged with `deleted_at`, never physically removed.
 *  - An audit trail — `created_by` / `updated_by` / `deleted_by` are stamped
 *    automatically with the authenticated user id in {@see boot()}.
 *  - Consistent "Y-m-d H:i:s" datetime serialization.
 *
 * (Mirrors the role of Acodax's App\Models\AppModel, trimmed to what this
 * project actually needs — no media library, activity log or branch scoping.)
 */
abstract class AppModel extends Model
{
    use HasFactory;
    use HasVersion4Uuids;
    use SoftDeletes;

    /**
     * Register model lifecycle hooks that stamp the audit columns.
     *
     * Each stamp is guarded by Schema::hasColumn so a model whose table has no
     * audit columns simply skips it, and by an authenticated user so writes
     * from seeders, factories or the console leave the columns null.
     */
    protected static function boot(): void
    {
        parent::boot();

        static::creating(function (self $model): void {
            $model->stampAuditColumn('created_by');
            $model->stampAuditColumn('updated_by');
        });

        static::updating(function (self $model): void {
            $model->stampAuditColumn('updated_by');
        });

        static::deleting(function (self $model): void {
            if ($model->stampAuditColumn('deleted_by')) {
                // Persist deleted_by without firing further events; the soft
                // delete's own UPDATE only writes deleted_at/updated_at.
                $model->saveQuietly();
            }
        });
    }

    /**
     * Set an audit column to the current user id when the column exists, the
     * caller is authenticated, and the value has not been set explicitly.
     *
     * @return bool whether the column was stamped
     */
    protected function stampAuditColumn(string $column): bool
    {
        if ($this->isDirty($column)) {
            return false;
        }

        if (! auth()->check() || ! Schema::hasColumn($this->getTable(), $column)) {
            return false;
        }

        $this->{$column} = auth()->id();

        return true;
    }

    /**
     * Serialize dates as "Y-m-d H:i:s" instead of Eloquent's default ISO-8601.
     *
     * ISO-8601 is not round-trippable through some Carbon helpers, and a flat
     * "Y-m-d H:i:s" is friendlier for clients reading the raw model array.
     * API payloads format their own timestamps in the Resource layer, so this
     * only affects direct model-to-array serialization.
     */
    protected function serializeDate(DateTimeInterface $date): string
    {
        return $date->format('Y-m-d H:i:s');
    }

    /**
     * The user who created the record.
     *
     * @return BelongsTo<User, $this>
     */
    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    /**
     * The user who last updated the record.
     *
     * @return BelongsTo<User, $this>
     */
    public function editor(): BelongsTo
    {
        return $this->belongsTo(User::class, 'updated_by');
    }
}
